Applied rofi theme for all rofi scripts

diff --git a/hypr/scripts/passmenu b/hypr/scripts/passmenu
--- a/hypr/scripts/passmenu
+++ b/hypr/scripts/passmenu
@@ -4,17 +4,17 @@ shopt -s nullglob globstar
 
 typeit=0
 if [[ $1 == "--type" ]]; then
-	typeit=1
-	shift
+  typeit=1
+  shift
 fi
 
 if [[ -n $WAYLAND_DISPLAY ]]; then
-	xdotool="ydotool type --file -"
+  xdotool="ydotool type --file -"
 elif [[ -n $DISPLAY ]]; then
-	xdotool="xdotool type --clearmodifiers --file -"
+  xdotool="xdotool type --clearmodifiers --file -"
 else
-	echo "Error: No Wayland or X11 display detected" >&2
-	exit 1
+  echo "Error: No Wayland or X11 display detected" >&2
+  exit 1
 fi
 
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
@@ -22,7 +22,7 @@ password_files=( "$prefix"/**/*.gpg )
 password_files=( "${password_files[@]#"$prefix"/}" )
 password_files=( "${password_files[@]%.gpg}" )
 
-password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu "$@")
+password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu "$@" -p "🔑 " -theme "$XDG_CONFIG_HOME/rofi/themes/no-icon.rasi" -theme-str "window {width: 13%;}")
 
 [[ -n $password ]] || exit
 
@@ -35,6 +35,6 @@ if [[ $typeit -eq 0 ]]; then
     pass show -c "$password" 2>/dev/null
   fi
 else
-	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
+  pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
 fi
 copyq enable
